name: certs renewal
  when: ssl_renewal == True
  shell: certbot renew --non-interactive

{% for item in ssl %}

- name: check cert
  stat:
    path: /etc/letsencrypt/live/{{ item }}/fullchain.pem
  register: cert_exists
  changed_when: False

- name: Set fact of SSL certificates
  set_fact:
    ssl_exist: "{{ cert_exists.stat.exists }}"

- name: renew cert
  tags: molecule-notest
  when: ssl_exist == False and ssl_renewal == True
    shell: certbot certonly --webroot --register-unsafely-without-email --agree-tos --non-interactive --webroot-path /var/www/{{ item }} --domains {{ item }}
  notify: reload nginx

- name: Flush handlers
  meta: flush_handlers

{% endfor %}

- name: check renewal
  stat:
    path: /etc/cron.d/certbot
  register: check_renewal
  changed_when: False
  

- name: auto renew SSL certificates by cron
  when: check_renewal.stat.exists == True
  copy:
    src: certbot
    dest: /etc/cron.d/certbot
