- name: install nginx
  apt:
    name: nginx
    update_cache: True

- name: Start nginx
  service:
    name: 
      - nginx
      - certbot
    state: started
    enabled: yes

- name: copy nginx config
  when: configs != False
  copy:
    src: {{ configs }}
    dest: /etc/nginx/
  notify: reload nginx

-name: disable default host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: vhost activation
  file:
  when: vhosts != False
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  loop: {{ vhosts }}
  notify: reload nginx

- name: Flush handlers
  meta: flush_handlers
