- name: install nginx and certbot
  apt:
    name: '{{ item }}'
    update_cache: True
  loop:
    - nginx
    - certbot

- name: Start nginx and certbot
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - nginx
    - certbot
  ignore_errors: yes

- name: check certs
  when: server in vhosts or server in ssl or ssl_renewal == True
  include_tasks: check_cert.yml

- name: Remove default site content and conf
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/etc/nginx/sites-available/default'
    - '/etc/nginx/sites-enabled/default'
    - '/var/www/html'

- name: configure nginx
  when: configs != False
  include_tasks: configuration.yml

- name: vhost activation
  when: vhosts != False
  include_tasks: vhost_activation.yml
  loop: '{{ vhosts }}'

- name: Flush handlers
  meta: flush_handlers

- name: certs renewal
  when: ssl_renewal == True
  include_tasks: renew_cert.yml

- name: add cert
  when: server in ssl
  include_tasks: add_cert.yml

- name: Flush handlers
  meta: flush_handlers

- name: check renewal
  stat:
    path: /etc/cron.d/certbot
  register: check_renewal  

- name: auto renew SSL certificates by cron
  when: check_renewal.stat.exists == True
  copy:
    src: certbot
    dest: /etc/cron.d/certbot
