---
- name: nginx and users
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    server: "{{ inventory_hostname }}"

  vars_files:
    - "host_vars/{{ server }}.yml"
    - secrets/common.vault
    - host_vars/common.yml

  tasks:
  
  - name: create content folder
    file:
      path: /var/www/{{ server }}
      mode: 0755

  - name: copy site content
    copy:
      src: ../host_files/index.nginx-debian.html
      dest: /var/www/{{ server }}/index.nginx-debian.html
      mode: 0755

  roles:
    - role: nginx
      configs: 'host_files/configs/nginx.conf'
      ssl_renewal: True
      ssl:
        - domain1.com
        - domain2.com
      vhosts:
        - uberlegenheit
        - biba.uberlegenheit.ru
