---
- name: nginx and users
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    server: "{{ inventory_hostname }}"

  vars_files:
    - "host_vars/{{ server }}.yml"
    - secrets/common.vault
    - host_vars/common.yml

  tasks:
  
  - name: create content folder
    file:
      path: /var/www/{{ server }}.{{region}}
      mode: 0755
      state: directory

  - name: copy site content
    copy:
      src: ./host_files/{{ server }}.html
      dest: /var/www/{{ server }}.{{region}}/index.nginx-debian.html
      mode: 0755

  roles:
    - role: nginx
      configs: 'host_files/configs/nginx.conf'
      ssl_renewal: True
      ssl:
        - domain1.com
        - domain2.com
      vhosts:
        - uberlegenheit.ru
        - biba.uberlegenheit.ru

    - role: users
      username: 'padavan'
      password: 'my_parol'
      sudo: 'yes'
      sudoers: '/usr/bin/nano,/usr/bin/systemctl'
      ssh_key: '{{ ssh_keys }}'
