---
- name: nginx and users
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    server: "{{ inventory_hostname }}"

  vars_files:
    - "host_vars/{{ server }}.yml"
    - secrets/common.vault
    - host_vars/common.yml

  tasks:
  
  roles:
    - role: users
      username: 'padavan'
      password: '$6$qs1.rWWivsLrxXeB$aBq2bZv6nudNJTcN/A4GnslFY94sAE1cbe7KqKU6lVRGU2IbpxDIXYE8fCzlr/HrxmZsVETKbgRueF5UyHBWP.'
      sudo: True
      sudoers: 
        - '/usr/bin/nano'
        - '/usr/bin/systemctl'
      ssh_key: '{{ ssh_keys }}'
