---
- name: nginx and users
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    server: "{{ inventory_hostname }}"

  vars_files:
    - "host_vars/{{ server }}.yml"
    # - secrets/common.vault
    - host_vars/common.yml

  pre_tasks:
  
  - name: create content folder
    file:
      path: /var/www/{{ item }}
      mode: 0755
      state: directory
    loop: '{{ ssl_ }}'

  - name: copy site content
    copy:
      src: ./host_files/host_01.html
      dest: /var/www/{{ item }}/index.nginx-debian.html
      mode: 0755
    loop: '{{ ssl_ }}'

  roles:
    - role: nginx
      configs: '{{ configs_ }}'
      ssl_renewal: '{{ ssl_renewal_ }}'
      ssl: '{{ ssl_ }}'
      vhosts: '{{ vhosts_ }}'

    - role: users
      username: '{{ username_ }}'
      password: '{{ password_ }}'
      sudo: '{{ sudo_ }}'
      sudoers: '{{ sudoers_ }}'
      ssh_key: '{{ ssh_key_ }}'
